/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function echoInt32Array(someInputCoordinates: Array<Int32Array>): Array<Int32Array>
export function echoInt32ArrayAsync(someInputCoordinates: Array<Int32Array>): Promise<unknown>
export function echoInt32ArrayAsArrayAsync(someInputCoordinates: Array<Int32Array>): Promise<unknown>
